name: Run E2E test

on:
  workflow_run:
    workflows:
      - "Deploy to Staging"
    types:
      - completed

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Playwright dependencies
        run: npx playwright install-deps
        working-directory: ./e2e

      - name: Setup E2E test
        run: npm ci
        working-directory: ./e2e

      - name: Run E2E test
        run: npm run test
        working-directory: ./e2e
        env:
          BASE_URL: 'https://fastify-webapp-sample-staging.up.railway.app/'
          HEADLESS: true

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: e2e/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
